litellm_settings:
  custom_provider_map:
  - provider: yoda_speak
    custom_handler: yoda_example.yoda_speak.yoda_speak_llm

model_list:
  - model_name: yoda
    litellm_params:
      model: yoda_speak/yoda
      drop_params: true  # Automatically drop unsupported parameters
