"# LiteLLM config using a single CustomLLMHandler.\n"
"# The handler maps friendly model names to provider models dynamically,\n"
"# so no per-model mappings are required here.\n"

# Keep an empty list; routing is handled by the custom handler.
model_list: []

# Register the custom handler. LiteLLM will import this and call its
# completion/acompletion methods. Different LiteLLM versions support
# slightly different keys; we include the commonly-supported ones.
litellm_settings:
  # Path to the handler in `<file>:<ClassName>` form. The file path is
  # relative to the working directory when you run `litellm`.
  custom_llm_handler: ./src/custom_llm_handler.py:CustomLLMHandler

# Some versions look under `router` for the custom handler; this is a
# no-op if unsupported and keeps the config portable.
router:
  custom_llm_handler: ./src/custom_llm_handler.py:CustomLLMHandler

