model_list:
  - model_name: gpt-5-reason-minimal
    litellm_params:
      model: openai/gpt-5
      reasoning_effort: minimal

  - model_name: gpt-5-reason-low
    litellm_params:
      model: openai/gpt-5
      reasoning_effort: low

  - model_name: gpt-5-reason-medium
    litellm_params:
      model: openai/gpt-5
      reasoning_effort: medium

  - model_name: gpt-5-reason-high
    litellm_params:
      model: openai/gpt-5
      reasoning_effort: high

  - model_name: gpt-5-mini-reason-minimal
    litellm_params:
      model: openai/gpt-5-mini
      reasoning_effort: minimal

  - model_name: gpt-5-mini-reason-low
    litellm_params:
      model: openai/gpt-5-mini
      reasoning_effort: low

  - model_name: gpt-5-mini-reason-medium
    litellm_params:
      model: openai/gpt-5-mini
      reasoning_effort: medium

  - model_name: gpt-5-mini-reason-high
    litellm_params:
      model: openai/gpt-5-mini
      reasoning_effort: high

  - model_name: gpt-5-nano-reason-minimal
    litellm_params:
      model: openai/gpt-5-nano
      reasoning_effort: minimal

  - model_name: gpt-5-nano-reason-low
    litellm_params:
      model: openai/gpt-5-nano
      reasoning_effort: low

  - model_name: gpt-5-nano-reason-medium
    litellm_params:
      model: openai/gpt-5-nano
      reasoning_effort: medium

  - model_name: gpt-5-nano-reason-high
    litellm_params:
      model: openai/gpt-5-nano
      reasoning_effort: high

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022

  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514

  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
