model_list:
  - model_name: "*"
    litellm_params:
      # Route everything through a single custom handler.
      # The handler inspects the requested model name and forwards to the
      # correct provider/model with any needed params (e.g., reasoning_effort).
      model: custom/claude-code-router
      custom_llm_provider: src.custom_llm_handler:CustomLLMHandler
