services:
  claude-code-gpt-5:

    image: ghcr.io/teremterem/claude-code-gpt-5:latest
    # # If you want to build the image from source, comment out the line above
    # # and uncomment the line below
    # build: .

    container_name: claude-code-gpt-5
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
