services:
  api:
    depends_on:
      - litellm
      - mongodb
      - rag_api
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
    env_file:
      # Load .env from Claude Code GPT-5 Proxy (for the sake of
      # LITELLM_MASTER_KEY)
      - ../.env
      # Load .env from LibreChat (will take precedence in case of variable name
      # conflicts)
      - .env
    environment:
      - LITELLM_BASE_URL=http://litellm:4000/v1
      # # TODO Any way to fall back to the following if LITELLM_MASTER_KEY is
      # #  not set in ../.env ?
      # - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-my-non-secure-litellm-master-key}

  litellm:
    # Build from Claude Code GPT-5 Proxy
    build: ..
    container_name: litellm
    # ports:
    #   - "4000:4000"
    restart: unless-stopped
    volumes:
      - ..:/app
      - litellm-app-venv:/app/.venv
      # To boost performance of `uv sync` operation
      - litellm-uv-cache:/root/.cache/uv
    env_file:
      - ../.env
    # # TODO Any way to fall back to the following if LITELLM_MASTER_KEY is
    # #  not set in ../.env ?
    # environment:
    #   - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-my-non-secure-litellm-master-key}

volumes:
  litellm-app-venv:
  litellm-uv-cache:
