services:
  litellm:
    # Build from Claude Code GPT-5 Proxy
    build: ..
    volumes:
      - ..:/app
      - litellm-app-venv:/app/.venv
      # To boost performance of `uv sync` operation
      - litellm-uv-cache:/root/.cache/uv
    container_name: LiteLLM-Server
    # ports:
    #   - "4000:4000"
    restart: unless-stopped
    env_file:
      # A dummy value for LITELLM_MASTER_KEY to avoid error if it is not set in
      # ../.env (the .env of Claude Code GPT-5 Proxy itself)
      - .env.non-secure-litellm-master-key
      # If LITELLM_MASTER_KEY is set in ../.env, it will override the dummy
      # value from the file above
      - ../.env

  api:
    # Let's pin LibreChat to a specific image version
    image: ghcr.io/danny-avila/librechat:v0.8.0
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
    depends_on:
      - litellm
      - mongodb
      - rag_api
    env_file:
      # A dummy value for LITELLM_MASTER_KEY to avoid error if it is not set in
      # ../.env (the .env of Claude Code GPT-5 Proxy itself)
      - .env.non-secure-litellm-master-key
      # If LITELLM_MASTER_KEY is set in ../.env, it will override the dummy
      # value from the file above
      - ../.env
      # Load .env from LibreChat (will override everything else in case of
      # variable name conflicts)
      - .env
    environment:
      - LITELLM_BASE_URL=http://litellm:4000/v1

  rag_api:
    # Let's pin LibreChat RAG API to a specific image version
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:v0.6.0
    # TODO 2025-10-14: The "latest" version of LibreChat RAG API (which is
    #  referenced in the original docker-compose.yml file) was built almost one
    #  month later, than the most recent numbered version "v0.6.0", but does
    #  not have its own version number.
    #  Should we go back to using "latest" instead of "v0.6.0" ?
    #  Is there any difference between the two ?

volumes:
  litellm-app-venv:
  litellm-uv-cache:
